// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 4.3Gauge

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void connectCAN(lv_event_t * e);
void pollCAN(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
