// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 4.3Gauge

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

void connectCAN(lv_event_t * e);
void pollCAN(lv_event_t * e);
void settingsButton(lv_event_t * e);
void wifiAPstart(lv_event_t * e);
void ui_events_post_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
