// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 4.3Gauge

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_connectCAN = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_gauge1 = NULL;
lv_obj_t * ui_piddropdown1 = NULL;
lv_obj_t * ui_unitdropdown1 = NULL;
lv_obj_t * ui_gaugeText1 = NULL;
lv_obj_t * ui_vehicleInfoLabel1 = NULL;
lv_obj_t * ui_pollCAN1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_statusLabel1 = NULL;
lv_obj_t * ui_gauge2 = NULL;
lv_obj_t * ui_piddropdown2 = NULL;
lv_obj_t * ui_unitdropdown2 = NULL;
lv_obj_t * ui_gaugeText2 = NULL;
lv_obj_t * ui_gauge3 = NULL;
lv_obj_t * ui_piddropdown3 = NULL;
lv_obj_t * ui_unitdropdown3 = NULL;
lv_obj_t * ui_gaugeText3 = NULL;
lv_obj_t * ui_gauge4 = NULL;
lv_obj_t * ui_piddropdown4 = NULL;
lv_obj_t * ui_unitdropdown4 = NULL;
lv_obj_t * ui_gaugeText4 = NULL;
lv_obj_t * ui_settingsButton = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_connectCAN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        connectCAN(e);
    }
}

void ui_event_pollCAN1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pollCAN(e);
    }
}

void ui_event_settingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectCAN = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_connectCAN, lv_pct(20));
    lv_obj_set_height(ui_connectCAN, lv_pct(5));
    lv_obj_set_align(ui_connectCAN, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_connectCAN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_connectCAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_connectCAN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connectCAN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_connectCAN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_connectCAN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_connectCAN, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_connectCAN);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Connect");

    ui_gauge1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_gauge1, lv_pct(30));
    lv_obj_set_height(ui_gauge1, lv_pct(30));
    lv_obj_set_x(ui_gauge1, lv_pct(-15));
    lv_obj_set_y(ui_gauge1, lv_pct(-20));
    lv_obj_set_align(ui_gauge1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gauge1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_gauge1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gauge1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gauge1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gauge1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gauge1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_piddropdown1 = lv_dropdown_create(ui_gauge1);
    lv_dropdown_set_options(ui_piddropdown1, "PID NAME ");
    lv_obj_set_width(ui_piddropdown1, lv_pct(135));
    lv_obj_set_height(ui_piddropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_piddropdown1, lv_pct(0));
    lv_obj_set_y(ui_piddropdown1, lv_pct(-17));
    lv_obj_set_align(ui_piddropdown1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_piddropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_piddropdown1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_piddropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_piddropdown1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_piddropdown1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_piddropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_piddropdown1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_piddropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_piddropdown1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_unitdropdown1 = lv_dropdown_create(ui_gauge1);
    lv_dropdown_set_options(ui_unitdropdown1, "PID UNIT");
    lv_obj_set_width(ui_unitdropdown1, lv_pct(135));
    lv_obj_set_height(ui_unitdropdown1, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_unitdropdown1, lv_pct(0));
    lv_obj_set_y(ui_unitdropdown1, lv_pct(17));
    lv_obj_set_align(ui_unitdropdown1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_unitdropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_unitdropdown1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_unitdropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_unitdropdown1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_unitdropdown1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_unitdropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_unitdropdown1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_unitdropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_unitdropdown1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gaugeText1 = lv_label_create(ui_gauge1);
    lv_obj_set_width(ui_gaugeText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gaugeText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gaugeText1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_gaugeText1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vehicleInfoLabel1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_vehicleInfoLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vehicleInfoLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vehicleInfoLabel1, lv_pct(0));
    lv_obj_set_y(ui_vehicleInfoLabel1, lv_pct(10));
    lv_obj_set_align(ui_vehicleInfoLabel1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_vehicleInfoLabel1, "Vehicle Info");

    ui_pollCAN1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_pollCAN1, lv_pct(20));
    lv_obj_set_height(ui_pollCAN1, lv_pct(5));
    lv_obj_set_align(ui_pollCAN1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_pollCAN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pollCAN1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pollCAN1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pollCAN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pollCAN1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pollCAN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pollCAN1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_pollCAN1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Poll");

    ui_statusLabel1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_statusLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statusLabel1, 0);
    lv_obj_set_y(ui_statusLabel1, -30);
    lv_obj_set_align(ui_statusLabel1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_statusLabel1, "Status");

    ui_gauge2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_gauge2, lv_pct(30));
    lv_obj_set_height(ui_gauge2, lv_pct(30));
    lv_obj_set_x(ui_gauge2, lv_pct(-15));
    lv_obj_set_y(ui_gauge2, lv_pct(20));
    lv_obj_set_align(ui_gauge2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gauge2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_gauge2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gauge2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gauge2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gauge2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gauge2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_piddropdown2 = lv_dropdown_create(ui_gauge2);
    lv_dropdown_set_options(ui_piddropdown2, "PID NAME ");
    lv_obj_set_width(ui_piddropdown2, lv_pct(135));
    lv_obj_set_height(ui_piddropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_piddropdown2, lv_pct(0));
    lv_obj_set_y(ui_piddropdown2, lv_pct(-17));
    lv_obj_set_align(ui_piddropdown2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_piddropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_piddropdown2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_piddropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_piddropdown2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_piddropdown2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_piddropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_piddropdown2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_piddropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_piddropdown2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_unitdropdown2 = lv_dropdown_create(ui_gauge2);
    lv_dropdown_set_options(ui_unitdropdown2, "PID UNIT");
    lv_obj_set_width(ui_unitdropdown2, lv_pct(135));
    lv_obj_set_height(ui_unitdropdown2, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_unitdropdown2, lv_pct(0));
    lv_obj_set_y(ui_unitdropdown2, lv_pct(17));
    lv_obj_set_align(ui_unitdropdown2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_unitdropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_unitdropdown2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_unitdropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_unitdropdown2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_unitdropdown2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_unitdropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_unitdropdown2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_unitdropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_unitdropdown2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gaugeText2 = lv_label_create(ui_gauge2);
    lv_obj_set_width(ui_gaugeText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gaugeText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gaugeText2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_gaugeText2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gauge3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_gauge3, lv_pct(30));
    lv_obj_set_height(ui_gauge3, lv_pct(30));
    lv_obj_set_x(ui_gauge3, lv_pct(15));
    lv_obj_set_y(ui_gauge3, lv_pct(-20));
    lv_obj_set_align(ui_gauge3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gauge3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_gauge3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gauge3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gauge3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gauge3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gauge3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_piddropdown3 = lv_dropdown_create(ui_gauge3);
    lv_dropdown_set_options(ui_piddropdown3, "PID NAME ");
    lv_obj_set_width(ui_piddropdown3, lv_pct(135));
    lv_obj_set_height(ui_piddropdown3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_piddropdown3, lv_pct(0));
    lv_obj_set_y(ui_piddropdown3, lv_pct(-17));
    lv_obj_set_align(ui_piddropdown3, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_piddropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_piddropdown3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_piddropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_piddropdown3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_piddropdown3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_piddropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_piddropdown3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_piddropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_piddropdown3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_unitdropdown3 = lv_dropdown_create(ui_gauge3);
    lv_dropdown_set_options(ui_unitdropdown3, "PID UNIT");
    lv_obj_set_width(ui_unitdropdown3, lv_pct(135));
    lv_obj_set_height(ui_unitdropdown3, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_unitdropdown3, lv_pct(0));
    lv_obj_set_y(ui_unitdropdown3, lv_pct(17));
    lv_obj_set_align(ui_unitdropdown3, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_unitdropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_unitdropdown3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_unitdropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_unitdropdown3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_unitdropdown3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_unitdropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_unitdropdown3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_unitdropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_unitdropdown3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gaugeText3 = lv_label_create(ui_gauge3);
    lv_obj_set_width(ui_gaugeText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gaugeText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gaugeText3, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_gaugeText3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gauge4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_gauge4, lv_pct(30));
    lv_obj_set_height(ui_gauge4, lv_pct(30));
    lv_obj_set_x(ui_gauge4, lv_pct(15));
    lv_obj_set_y(ui_gauge4, lv_pct(20));
    lv_obj_set_align(ui_gauge4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gauge4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_gauge4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gauge4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gauge4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gauge4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gauge4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_piddropdown4 = lv_dropdown_create(ui_gauge4);
    lv_dropdown_set_options(ui_piddropdown4, "PID NAME ");
    lv_obj_set_width(ui_piddropdown4, lv_pct(135));
    lv_obj_set_height(ui_piddropdown4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_piddropdown4, lv_pct(0));
    lv_obj_set_y(ui_piddropdown4, lv_pct(-17));
    lv_obj_set_align(ui_piddropdown4, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_piddropdown4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_piddropdown4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_piddropdown4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_piddropdown4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_piddropdown4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_piddropdown4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_piddropdown4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_piddropdown4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_piddropdown4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_unitdropdown4 = lv_dropdown_create(ui_gauge4);
    lv_dropdown_set_options(ui_unitdropdown4, "PID UNIT");
    lv_obj_set_width(ui_unitdropdown4, lv_pct(135));
    lv_obj_set_height(ui_unitdropdown4, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_unitdropdown4, lv_pct(0));
    lv_obj_set_y(ui_unitdropdown4, lv_pct(17));
    lv_obj_set_align(ui_unitdropdown4, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_unitdropdown4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_unitdropdown4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_unitdropdown4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_unitdropdown4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_unitdropdown4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_unitdropdown4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_unitdropdown4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_unitdropdown4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_unitdropdown4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gaugeText4 = lv_label_create(ui_gauge4);
    lv_obj_set_width(ui_gaugeText4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gaugeText4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gaugeText4, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_gaugeText4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_settingsButton, lv_pct(20));
    lv_obj_set_height(ui_settingsButton, lv_pct(5));
    lv_obj_set_x(ui_settingsButton, lv_pct(0));
    lv_obj_set_y(ui_settingsButton, lv_pct(3));
    lv_obj_set_align(ui_settingsButton, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_settingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_settingsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_settingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_settingsButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_settingsButton);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Settings");

    lv_obj_add_event_cb(ui_connectCAN, ui_event_connectCAN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pollCAN1, ui_event_pollCAN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsButton, ui_event_settingsButton, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_connectCAN = NULL;
    ui_Label1 = NULL;
    ui_gauge1 = NULL;
    ui_piddropdown1 = NULL;
    ui_unitdropdown1 = NULL;
    ui_gaugeText1 = NULL;
    ui_vehicleInfoLabel1 = NULL;
    ui_pollCAN1 = NULL;
    ui_Label2 = NULL;
    ui_statusLabel1 = NULL;
    ui_gauge2 = NULL;
    ui_piddropdown2 = NULL;
    ui_unitdropdown2 = NULL;
    ui_gaugeText2 = NULL;
    ui_gauge3 = NULL;
    ui_piddropdown3 = NULL;
    ui_unitdropdown3 = NULL;
    ui_gaugeText3 = NULL;
    ui_gauge4 = NULL;
    ui_piddropdown4 = NULL;
    ui_unitdropdown4 = NULL;
    ui_gaugeText4 = NULL;
    ui_settingsButton = NULL;
    ui_Label3 = NULL;

}
