// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 4.3Gauge

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_brightnessSlider = NULL;
lv_obj_t * ui_brightnessLabel = NULL;
lv_obj_t * ui_backButton = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_systemPanel = NULL;
lv_obj_t * ui_colorWhellPanel = NULL;
lv_obj_t * ui_wifiAPstartButton1 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_brightnessSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_text_value(ui_brightnessLabel, target, "", "");
    }
}

void ui_event_backButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_wifiAPstartButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        wifiAPstart(e);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_brightnessSlider = lv_slider_create(ui_Screen2);
    lv_slider_set_value(ui_brightnessSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_brightnessSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_brightnessSlider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_brightnessSlider, lv_pct(75));
    lv_obj_set_height(ui_brightnessSlider, lv_pct(5));
    lv_obj_set_x(ui_brightnessSlider, lv_pct(0));
    lv_obj_set_y(ui_brightnessSlider, lv_pct(20));
    lv_obj_set_align(ui_brightnessSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_brightnessSlider, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightnessSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_brightnessSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_brightnessSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_brightnessSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_brightnessSlider, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_brightnessSlider, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightnessSlider, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_brightnessSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightnessSlider, 100, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_brightnessLabel = lv_label_create(ui_brightnessSlider);
    lv_obj_set_width(ui_brightnessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brightnessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_brightnessLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brightnessLabel, "Brightness");
    lv_obj_set_style_text_color(ui_brightnessLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_brightnessLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_backButton, lv_pct(12));
    lv_obj_set_height(ui_backButton, lv_pct(5));
    lv_obj_set_x(ui_backButton, lv_pct(0));
    lv_obj_set_y(ui_backButton, lv_pct(-6));
    lv_obj_set_align(ui_backButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_backButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_backButton);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Back");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_systemPanel, lv_pct(40));
    lv_obj_set_height(ui_systemPanel, lv_pct(40));
    lv_obj_set_x(ui_systemPanel, lv_pct(-20));
    lv_obj_set_y(ui_systemPanel, lv_pct(-7));
    lv_obj_set_align(ui_systemPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_systemPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_systemPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_systemPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_colorWhellPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_colorWhellPanel, lv_pct(40));
    lv_obj_set_height(ui_colorWhellPanel, lv_pct(40));
    lv_obj_set_x(ui_colorWhellPanel, lv_pct(21));
    lv_obj_set_y(ui_colorWhellPanel, lv_pct(-7));
    lv_obj_set_align(ui_colorWhellPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_colorWhellPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_colorWhellPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_colorWhellPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiAPstartButton1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_wifiAPstartButton1, lv_pct(25));
    lv_obj_set_height(ui_wifiAPstartButton1, lv_pct(5));
    lv_obj_set_x(ui_wifiAPstartButton1, lv_pct(0));
    lv_obj_set_y(ui_wifiAPstartButton1, lv_pct(5));
    lv_obj_set_align(ui_wifiAPstartButton1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_wifiAPstartButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiAPstartButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiAPstartButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiAPstartButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifiAPstartButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifiAPstartButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifiAPstartButton1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_wifiAPstartButton1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "WiFi Settings");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_brightnessSlider, ui_event_brightnessSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backButton, ui_event_backButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiAPstartButton1, ui_event_wifiAPstartButton1, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_brightnessSlider = NULL;
    ui_brightnessLabel = NULL;
    ui_backButton = NULL;
    ui_Label4 = NULL;
    ui_systemPanel = NULL;
    ui_colorWhellPanel = NULL;
    ui_wifiAPstartButton1 = NULL;
    ui_Label5 = NULL;

}
