// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 4.3Gauge

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern void ui_event_brightnessSlider(lv_event_t * e);
extern lv_obj_t * ui_brightnessSlider;
extern lv_obj_t * ui_brightnessLabel;
extern void ui_event_backButton(lv_event_t * e);
extern lv_obj_t * ui_backButton;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_systemPanel;
extern lv_obj_t * ui_colorWhellPanel;
extern void ui_event_wifiAPstartButton1(lv_event_t * e);
extern lv_obj_t * ui_wifiAPstartButton1;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

