// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 4.3Gauge

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_connectCAN = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_gauge1 = NULL;
lv_obj_t * ui_piddropdown1 = NULL;
lv_obj_t * ui_unnitdropdown2 = NULL;
lv_obj_t * ui_gaugeText1 = NULL;
lv_obj_t * ui_vehicleInfoLabel1 = NULL;
// event funtions
void ui_event_connectCAN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        connectCAN(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectCAN = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_connectCAN, lv_pct(20));
    lv_obj_set_height(ui_connectCAN, lv_pct(15));
    lv_obj_set_x(ui_connectCAN, lv_pct(-15));
    lv_obj_set_y(ui_connectCAN, lv_pct(0));
    lv_obj_set_align(ui_connectCAN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_connectCAN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_connectCAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_connectCAN);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Connect");

    ui_gauge1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_gauge1, lv_pct(39));
    lv_obj_set_height(ui_gauge1, lv_pct(55));
    lv_obj_set_x(ui_gauge1, lv_pct(15));
    lv_obj_set_y(ui_gauge1, lv_pct(0));
    lv_obj_set_align(ui_gauge1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gauge1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_piddropdown1 = lv_dropdown_create(ui_gauge1);
    lv_obj_set_width(ui_piddropdown1, 150);
    lv_obj_set_height(ui_piddropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_piddropdown1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_piddropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_unnitdropdown2 = lv_dropdown_create(ui_gauge1);
    lv_obj_set_width(ui_unnitdropdown2, 150);
    lv_obj_set_height(ui_unnitdropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_unnitdropdown2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_unnitdropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_gaugeText1 = lv_label_create(ui_gauge1);
    lv_obj_set_width(ui_gaugeText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gaugeText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gaugeText1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_gaugeText1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vehicleInfoLabel1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_vehicleInfoLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vehicleInfoLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vehicleInfoLabel1, lv_pct(0));
    lv_obj_set_y(ui_vehicleInfoLabel1, lv_pct(5));
    lv_obj_set_align(ui_vehicleInfoLabel1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_vehicleInfoLabel1, "Vehicle Info");

    lv_obj_add_event_cb(ui_connectCAN, ui_event_connectCAN, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_connectCAN = NULL;
    ui_Label1 = NULL;
    ui_gauge1 = NULL;
    ui_piddropdown1 = NULL;
    ui_unnitdropdown2 = NULL;
    ui_gaugeText1 = NULL;
    ui_vehicleInfoLabel1 = NULL;

}
