// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 4.3Gauge

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_connectCAN(lv_event_t * e);
extern lv_obj_t * ui_connectCAN;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_gauge1;
extern lv_obj_t * ui_piddropdown1;
extern lv_obj_t * ui_unitdropdown1;
extern lv_obj_t * ui_gaugeText1;
extern lv_obj_t * ui_vehicleInfoLabel1;
extern void ui_event_pollCAN1(lv_event_t * e);
extern lv_obj_t * ui_pollCAN1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_gauge2;
extern lv_obj_t * ui_piddropdown2;
extern lv_obj_t * ui_unitdropdown2;
extern lv_obj_t * ui_gaugeText2;
extern lv_obj_t * ui_gauge3;
extern lv_obj_t * ui_piddropdown3;
extern lv_obj_t * ui_unitdropdown3;
extern lv_obj_t * ui_gaugeText3;
extern lv_obj_t * ui_gauge4;
extern lv_obj_t * ui_piddropdown4;
extern lv_obj_t * ui_unitdropdown4;
extern lv_obj_t * ui_gaugeText4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

